---
- name: 'Ensure packages'
  package:
    name:
      - 'systemd-journal-gateway'
    state: 'present'

- name: 'Ensure systemd-journal-remote config'
  include_tasks: 'server.yml'
  when: journald_server == ansible_facts['fqdn']

- name: 'Ensure systemd-journald config'
  template:
    src: 'journald.conf.j2'
    dest: '/etc/systemd/journald.conf'
    mode: 0664
  notify:
    - 'restart systemd-journald'

- meta: 'flush_handlers'

- name: 'Ensure systemd-journald directory'
  file:
    path: '/var/log/journal'
    state: 'directory'
    mode: 0755
    owner: 'root'
    group: 'systemd-journal'
    recurse: true

- name: 'Ensure systemd-journal-upload config'
  template:
    src: 'journal-upload.conf.j2'
    dest: '/etc/systemd/journal-upload.conf'
    mode: 0664
  notify:
    - 'restart systemd-journal-upload'

- name: 'Ensure systemd-journal-upload service'
  template:
    src: 'systemd-journal-upload.service.j2'
    dest: '/etc/systemd/system/systemd-journal-upload.service'
    mode: 0664
  notify:
    - 'restart systemd-journal-upload'

- name: 'Ensure service status'
  systemd:
    name: 'systemd-journal-upload'
    state: 'started'
    enabled: true
