---
- name: 'restart systemd-journal-remote'
  systemd:
    name: 'systemd-journal-remote'
    state: 'restarted'
    daemon_reload: true

- name: 'restart systemd-journal-upload'
  systemd:
    name: 'systemd-journal-upload'
    state: 'restarted'
    daemon_reload: true

- name: 'restart systemd-journald'
  systemd:
    name: 'systemd-journald'
    state: 'restarted'
